# Generated by Django 4.1 on 2022-09-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
    ]
